ignore:
  - .tox/
  - .venv/
  - dist/
  - node_modules/
  - vendor/
  - venv/

rule_settings:
  enable: [default]
  disable: [dont-import-test-modules]
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"

rules: []

metrics:
  quality_threshold: 25.0

github:
  ignore_labels:
    - sourcery-ignore
    - docs
  labels:
    - build-ignore
  request_review:
    origin: owner
    forked: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

proxy:
  no_ssl_verify: false
